import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

const handler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});

/**
 * Wrap handler to add COOP/COEP headers for crossOriginIsolated.
 */
export const onRequest: PagesFunction = async (context) => {
  const response = await handler(context);

  // clone response to modify headers
  const newResponse = new Response(response.body, response);
  newResponse.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  newResponse.headers.set('Cross-Origin-Embedder-Policy', 'credentialless');

  return newResponse;
};
